### ISSUE TITLE
Fiddler

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#23]
### 如何在`Fiddler Script`中修改`Cookie`

`cookie`其实就是`request` 中的一个`header`.
// 删除所有的`cookie`
`oSession.oRequest.headers.Remove("Cookie");`
 
// 新建`cookie`
`oSession.oRequest.headers.Add("Cookie", "username=testname;testpassword=P@ssword1");`

注意: `Fiddler script`不能直接删除或者编辑单独的一个`cookie`， 你需要用`replace`方法或者正则表达式的方法去操作`cookie`的`string`

``` C#
static function OnBeforeRequest(oSession: Session)
 { 
     if (oSession.HostnameIs('www.example.com') && oSession.uriContains('pagewithCookie') && oSession.oRequest.headers.Contains("Cookie")) 
     { 
     var sCookie = oSession.oRequest["Cookie"]; 
     //  用replace方法或者正则表达式的方法去操作cookie的string
     sCookie = sCookie.Replace("cookieName=", "ignoreme="); 
     oSession.oRequest["Cookie"] = sCookie; 
    } 
}
```
### 如何在`Fiddler Script`中修改`Request`中的`body`
- **方法一:**

``` C#
static function OnBeforeRequest(oSession: Session) 
{ 
    if(oSession.uriContains("http://www.cnblogs.com/TankXiao/"))
    {
        // 获取Request 中的body字符串
        var strBody=oSession.GetRequestBodyAsString();
        // 用正则表达式或者replace方法去修改string
        strBody=strBody.replace("1111","2222");
        // 弹个对话框检查下修改后的body               
FiddlerObject.alert(strBody);
        // 将修改后的body，重新写回Request中
        oSession.utilSetRequestBody(strBody);
    }
}
```
- **方法二:**
  提供了一个非常简单的方法，可以直接替换`body`中的数据
  `oSession.utilReplaceInRequest("1111", "2222");`

【参考】[Fiddler (二) Script 用法](http://www.cnblogs.com/TankXiao/archive/2012/04/25/2349049.html)

**Comment by zplus** [comment]
[Fiddler调式使用知多少(一)深入研究](http://www.cnblogs.com/tugenhua0707/p/4623317.html)
