### ISSUE TITLE
WebStorm something

### ISSUE THREAD

**Issue by wamxb** [wamxb/blog#25]
- 无法保存
  `This files have types: *._jb_old_ and *._jb_bak_.`
  `Appearance&Behavior` => `System Settings` => `Use "safe write".....`
  ![无法保存](http://i.stack.imgur.com/4VtWF.png)
- 光标不随意定位
  `Settings`->`Editor`中去掉`Allow placement of caret after end of line`。
- 启动的时候不打开工程文件
  `Settings`->`System Settings`去掉`Reopen last project on startup`.
- 用*标识编辑过的文件
  `Editor` –> `General` -> `Editor Tabs`选中`Mark modifyied tabs with asterisk`
- 删除长代码对齐白线
  `Editor` –> `Appearance` –> `Show vertical indent guides` 前面的勾去掉即可。
- 当前编辑文件定位
  > 方法1) 在编辑的所选文件按`ALT+F1`, 然后选择`PROJECT VIEW`
  > 方法2) 左侧 项目列表框 顶部的 定位图标

【参考】[PHPSTORM/IntelliJ IDEA 常用 设置配置优化](http://blog.csdn.net/fenglailea/article/details/12166617)

**Comment by zplus** [comment]
### plugin
CSSReorder 
A tool for sorting CSS properties in specific orde
